In [ ]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
X, y = make_regression(n_samples=200,n_features=3,n_informative=3,noise=10,random_state=42)

In [ ]:
df = pd.DataFrame(X, columns=[
    '10_percentage',
    '12_percentage',
    'cgpa'
])

df['lpa'] = y
df.head()

   10_percentage  12_percentage      cgpa         lpa
0       0.130741      -1.430141 -0.440044  -64.558855
1       1.502357      -0.269407  0.717542  154.776889
2       0.647689       0.496714 -0.138264   61.896041
3       0.341756      -0.759133  0.150394   16.485672
4       0.856399      -1.514847 -0.446515  -31.907412

In [ ]:
df.shape

(200, 4)

In [ ]:
# convert to realistic ranges
df['10_percentage'] = (df['10_percentage'] * 10 + 75).clip(50, 100)
df['12_percentage'] = (df['12_percentage'] * 10 + 75).clip(50, 100)
df['cgpa'] = (df['cgpa'] * 1.5 + 7).clip(4, 10)

# make salary positive
df['lpa'] = (df['lpa'] / 10 + 6).clip(2, 25)

df.head()

   10_percentage  12_percentage      cgpa        lpa
0      76.307406      60.698586  6.339933   2.000000
1      90.023571      72.305932  8.076313  21.477689
2      81.476885      79.967142  6.792604  12.189604
3      78.417560      67.408673  7.225591   7.648567
4      83.563988      59.851528  6.330228   2.809259

In [ ]:
X = df[['10_percentage', '12_percentage', 'cgpa']]
y = df['lpa']

In [ ]:
fig = px.scatter_3d(df, x='cgpa', y='12_percentage', z='lpa')

fig.show()

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(X_train,y_train)

LinearRegression()

In [ ]:
LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None)

LinearRegression()

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 2.5058695282760617
MSE 8.391176216057696
R2 score 0.7676776832508785

In [ ]:
# create grid
x = np.linspace(df['10_percentage'].min(), df['10_percentage'].max(), 20)
y = np.linspace(df['12_percentage'].min(), df['12_percentage'].max(), 20)

xGrid, yGrid = np.meshgrid(x, y)

# FIX cgpa at mean
cgpa_fixed = df['cgpa'].mean()

# create model input (VERY IMPORTANT)
final = np.vstack([
    xGrid.ravel(),
    yGrid.ravel(),
    np.full(xGrid.size, cgpa_fixed)
]).T

In [ ]:
fig = px.scatter_3d(df, x='cgpa', y='12_percentage', z='lpa')

z = lr.predict(final).reshape(len(x), len(y))

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names

In [ ]:
lr.coef_

array([0.45870817, 0.14266967, 2.9703132 ])

In [ ]:
lr.intercept_

np.float64(-57.92483537541107)